### PR TITLE
Split CI/non-CI builds without overriding Python package set with non-modules

### PR DESCRIPTION
**Pull request by lilyinstarlight**
This fixes issues with current nixpkgs master where all members of the Python package set are now required to be Python modules

Let me know if this is a reasonable approach or not! I just wanted to get something that worked to demonstrate the root problem

Related: #45

### CODE REVIEW

**Comment by thiagokokada** [comment]
Thanks for the PR. However, the reason why I override the `mypy` and `black` packages is not because the non-CI builds shouldn't run them, but because I don't want their overhead to be included in non-CI build (specially `mypy` used to be very expensive to build because `mypyc`). This could easily take dozens of minutes to build even in modern machines.

Nowadays I disable `mypyc` so the `mypyc` rebuilds is less expensive, however ideally we should still avoid including them in non-CI builds since they're useless.

**Comment by lilyinstarlight** [comment]
> Thanks for the PR. However, the reason why I override the `mypy` and `black` packages is not because the non-CI builds shouldn't run them, but because I don't want their overhead to be included in non-CI build (specially `mypy` used to be very expensive to build because `mypyc`). This could easily take dozens of minutes to build even in modern machines.

Okay, I did figure this was probably your reasoning for doing it like that. I'm not sure how you want to approach this then, since non-python-modules can no longer be in the `python.pkgs` set

Do you have ideas?

**Comment by thiagokokada** [comment]
> Do you have ideas?

To fix it right now I will probably just remove the overrides. I think I will eventually remove `poetry2nix` from this project. It seems a interesting project for more complex Python applications, however it doesn't make much sense for this project, and the maintaining overhead is high.

**Comment by thiagokokada** [comment]
Now that we are building `mypy` without `mypyc`, the build is actually reasonable fast. This seems the way to go for now.

Fixed in bdb31bb8f312ccc62f8c6708dfbea0dbf3e65755.

**Pull request closed without merging**
